"""coworker accounts documents tasks and usage

Revision: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cw_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject')
    )
    op.create_table('cw_audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cw_audit_events_owner_id'), 'cw_audit_events', ['owner_id'], unique=False)
    op.create_table('cw_daily_usage',
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('allocated_tokens', sa.Integer(), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'day')
    )
    op.create_table('cw_workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('cw_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['cw_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cw_documents_owner_id'), 'cw_documents', ['owner_id'], unique=False)
    op.create_table('cw_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('workflow_version', sa.String(length=40), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('output_language', sa.String(length=35), nullable=False),
    sa.Column('input_versions', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('event_sequence', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['cw_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index('cw_tasks_owner_created', 'cw_tasks', ['owner_id', 'created_at'], unique=False)
    op.create_index('cw_tasks_state_deadline', 'cw_tasks', ['state', 'deadline_at'], unique=False)
    op.create_table('cw_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cw_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'filename')
    )
    op.create_index(op.f('ix_cw_artifacts_owner_id'), 'cw_artifacts', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cw_artifacts_task_id'), 'cw_artifacts', ['task_id'], unique=False)
    op.create_table('cw_document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['cw_documents.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version')
    )
    op.create_index(op.f('ix_cw_document_versions_document_id'), 'cw_document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_cw_document_versions_owner_id'), 'cw_document_versions', ['owner_id'], unique=False)
    op.create_table('cw_model_attempts',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('reserved_tokens', sa.Integer(), nullable=False),
    sa.Column('charged_tokens', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['cw_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'attempt')
    )
    op.create_table('cw_outbox',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['cw_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_cw_outbox_delivered'), 'cw_outbox', ['delivered'], unique=False)
    op.create_table('cw_steps',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['cw_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'phase')
    )
    op.create_table('cw_task_events',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['cw_tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'sequence')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cw_task_events')
    op.drop_table('cw_steps')
    op.drop_index(op.f('ix_cw_outbox_delivered'), table_name='cw_outbox')
    op.drop_table('cw_outbox')
    op.drop_table('cw_model_attempts')
    op.drop_index(op.f('ix_cw_document_versions_owner_id'), table_name='cw_document_versions')
    op.drop_index(op.f('ix_cw_document_versions_document_id'), table_name='cw_document_versions')
    op.drop_table('cw_document_versions')
    op.drop_index(op.f('ix_cw_artifacts_task_id'), table_name='cw_artifacts')
    op.drop_index(op.f('ix_cw_artifacts_owner_id'), table_name='cw_artifacts')
    op.drop_table('cw_artifacts')
    op.drop_index('cw_tasks_state_deadline', table_name='cw_tasks')
    op.drop_index('cw_tasks_owner_created', table_name='cw_tasks')
    op.drop_table('cw_tasks')
    op.drop_index(op.f('ix_cw_documents_owner_id'), table_name='cw_documents')
    op.drop_table('cw_documents')
    op.drop_table('cw_workspaces')
    op.drop_table('cw_daily_usage')
    op.drop_index(op.f('ix_cw_audit_events_owner_id'), table_name='cw_audit_events')
    op.drop_table('cw_audit_events')
    op.drop_table('cw_accounts')
    # ### end Alembic commands ###
