"""approved email and calendar actions

Revision: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cw_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('capability', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_ciphertext', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cw_connections_owner_id'), 'cw_connections', ['owner_id'], unique=False)
    op.create_table('cw_oauth_attempts',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=20), nullable=False),
    sa.Column('verifier_ciphertext', sa.Text(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_index(op.f('ix_cw_oauth_attempts_owner_id'), 'cw_oauth_attempts', ['owner_id'], unique=False)
    op.create_table('cw_external_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('preview', sa.JSON(), nullable=False),
    sa.Column('preview_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('receipt', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['cw_connections.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['cw_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'idempotency_key')
    )
    op.create_index('cw_actions_dispatch', 'cw_external_actions', ['state', 'delivered', 'lease_until'], unique=False)
    op.create_index('cw_actions_owner_created', 'cw_external_actions', ['owner_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cw_actions_owner_created', table_name='cw_external_actions')
    op.drop_index('cw_actions_dispatch', table_name='cw_external_actions')
    op.drop_table('cw_external_actions')
    op.drop_index(op.f('ix_cw_oauth_attempts_owner_id'), table_name='cw_oauth_attempts')
    op.drop_table('cw_oauth_attempts')
    op.drop_index(op.f('ix_cw_connections_owner_id'), table_name='cw_connections')
    op.drop_table('cw_connections')
    # ### end Alembic commands ###
