'use client';
import { useEffect, useMemo, useRef } from 'react';
import type { Suggestion } from '@shuddho/shared';
import { checkText, trackSuggestion } from '../lib/api';
import { useEditorStore } from '../lib/editorStore';

function escapeHtml(value: string) {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function renderWithHighlights(text: string, suggestions: Suggestion[]) {
  const sorted = suggestions.filter((s) => s.endIndex <= text.length && s.startIndex < s.endIndex).sort((a, b) => a.startIndex - b.startIndex);
  let cursor = 0;
  let html = '';
  for (const suggestion of sorted) {
    if (suggestion.startIndex < cursor) continue;
    html += escapeHtml(text.slice(cursor, suggestion.startIndex));
    html += `<mark class="issue ${suggestion.type}" title="${escapeHtml(suggestion.explanation)}">${escapeHtml(text.slice(suggestion.startIndex, suggestion.endIndex))}</mark>`;
    cursor = suggestion.endIndex;
  }
  html += escapeHtml(text.slice(cursor));
  return html;
}

export function Editor() {
  const editorRef = useRef<HTMLDivElement>(null);
  const { documentId, revision, text, suggestions, status, setText, setSuggestions, accept, reject, setStatus } = useEditorStore();
  const html = useMemo(() => renderWithHighlights(text, suggestions), [text, suggestions]);

  useEffect(() => {
    const handle = window.setTimeout(async () => {
      setStatus('checking');
      try {
        const response = await checkText(text, documentId, revision);
        setSuggestions(response.suggestions);
        setStatus('synced');
      } catch {
        setStatus('offline');
      }
    }, 450);
    return () => window.clearTimeout(handle);
  }, [text, documentId, revision, setSuggestions, setStatus]);

  useEffect(() => {
    const wsUrl = (process.env.NEXT_PUBLIC_WS_URL ?? 'ws://localhost:4000/ws/docs').replace(/\/$/, '');
    const ws = new WebSocket(`${wsUrl}/${documentId}`);
    ws.onopen = () => ws.send(JSON.stringify({ type: 'delta', delta: { documentId, baseRevision: 0, clientOperationId: crypto.randomUUID(), op: { type: 'replace_all', text } } }));
    ws.onerror = () => setStatus('offline');
    return () => ws.close();
  }, [documentId]);

  return <div className="grid">
    <section className="editorCard">
      <div className="toolbar">
        <button type="button"><b>B</b></button>
        <button type="button"><i>I</i></button>
        <button type="button" className="primary" onClick={() => void checkText(text, documentId, revision).then((r) => setSuggestions(r.suggestions))}>Check now</button>
      </div>
      <div className="status"><span>Document revision {revision}</span><span>{status}</span></div>
      <div
        ref={editorRef}
        className="editor"
        contentEditable
        suppressContentEditableWarning
        dangerouslySetInnerHTML={{ __html: html }}
        onInput={(event) => setText(event.currentTarget.innerText)}
        aria-label="Writing editor"
      />
    </section>
    <aside className="sidePanel">
      <h2>Writing signals</h2>
      <p className="muted">Inline highlights are generated by local rules and mock AI providers through the backend gateway.</p>
      {suggestions.length === 0 ? <p>No active suggestions.</p> : suggestions.map((suggestion) => <article className="suggestion" key={suggestion.id}>
        <small>{suggestion.type.toUpperCase()} · {Math.round(suggestion.confidence * 100)}% · {suggestion.sourceProvider}</small>
        <strong>{suggestion.originalText || 'Selection'} → {suggestion.suggestedText}</strong>
        <p>{suggestion.explanation}</p>
        <div className="actions">
          <button className="accept" onClick={() => { accept(suggestion); void trackSuggestion('suggestion_accepted', suggestion, documentId); }}>Accept</button>
          <button onClick={() => { reject(suggestion); void trackSuggestion('suggestion_rejected', suggestion, documentId); }}>Reject</button>
        </div>
      </article>)}
    </aside>
  </div>;
}
