import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createApp } from '../dist/app.js';
const server = createServer(createApp()).listen(0);
await new Promise((resolve) => server.once('listening', resolve));
const { port } = server.address();
let response = await fetch(`http://127.0.0.1:${port}/health`);
assert.equal(response.status, 200);
response = await fetch(`http://127.0.0.1:${port}/api/check`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text: 'আমি  আমি ভাত খাই ।বাংলা ভাষা সুন্দর', language: 'bn', revision: 1, client: { surface: 'api' } }) });
assert.equal(response.status, 200);
const body = await response.json();
assert.ok(body.requestId);
assert.equal(body.language, 'bn');
assert.ok(body.suggestions.some((s) => s.ruleId === 'bn.spacing.repeated_spaces'));
assert.ok(body.suggestions.some((s) => s.ruleId === 'bn.grammar.duplicate_word'));
assert.ok(body.warnings.some((w) => String(w).includes('fallback')));
response = await fetch(`http://127.0.0.1:${port}/api/events`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ type: 'suggestion_accepted', language: 'bn', suggestionId: body.suggestions[0].id, metadata: { text: 'গোপন লেখা', textLength: 8 } }) });
assert.equal(response.status, 202);
await new Promise((resolve, reject) => server.close((err) => err ? reject(err) : resolve()));
console.log('API check tests passed');
